### ISSUE TITLE
403 error due to new authentication (solved)

### ISSUE THREAD

**Issue by weiqiyue** [fedebotu/youchat-google-extension#1]
![image](https://user-images.githubusercontent.com/63939219/210301523-6ba20040-3a2a-4c8a-84fe-c304a279f9fd.png)

**Comment by fedebotu** [comment]
Hi there, thanks for your feedback!
I checked it and I think they implemented a new cookie authentication system similar to ChatGPT
![image](https://user-images.githubusercontent.com/48984123/210324012-18ff18ae-7ca5-416b-9839-a787e4b7191b.png)

So we would need to get the cookie as in [this repository](https://github.com/wong2/chat-gpt-google-extension) and send it as part of the request... I won't have much spare time in the near future, so I hope someone could help with it

**Comment by fedebotu** [comment]
Hi @weiqiyue , it turns out the error could just be fixed by accessing Cloudflare first. Added new fix in latest release (v0.1.1) 👍🏼 Thanks again for your report!
