### ISSUE TITLE
Verifying

### ISSUE THREAD

**Issue by TheAppleGuyGamz** [fedebotu/youchat-google-extension#10]
Can you please make it so that cloudflare doesn't ask us to continuously verify again and again?

**Comment by fedebotu** [comment]
Unfortunately I don't think it is possible... It is annoying but there seems to be no way around it, similarly to the ChatGPT/Google extension :/

You may try logging in to you.com, that could help. A partial fix is mentioned in another issue (#9). Looking forward to suggestions
