### ISSUE TITLE
Not displayed in some cases

### ISSUE THREAD

**Issue by weiqiyue** [fedebotu/youchat-google-extension#3]
## domestic：
![image](https://user-images.githubusercontent.com/63939219/218360009-764849f2-f85f-4e83-877c-9e968c0d48bb.png)
## international：
![image](https://user-images.githubusercontent.com/63939219/218360029-31242130-007e-4565-90d4-c8b99e92aae3.png)
## consoles:
![image](https://user-images.githubusercontent.com/63939219/218360038-c69ce6a9-ca15-45be-bc2c-812a05fe2943.png)

**Comment by weiqiyue** [comment]
I'm sorry，I don't think I'm good at it, because I've never developed an extension 😢

**Comment by fedebotu** [comment]
@weiqiyue actually, me neither; this is my first one... fun fact I never studied Typescript. But by using some AI (Github Copilot, ChatGPT, YouChat itself) I managed to make something out of it ^^

**Comment by weiqiyue** [comment]
thank you, then take a look at your procedure and the program you mentioned, and then I close this first, after all, it does not affect the use
