### ISSUE TITLE
Please login and pass Cloudflare check at you.com

### ISSUE THREAD

**Issue by Raph844** [fedebotu/youchat-google-extension#5]
Here is what it write, but Login in You.com doesn't change anything, whelp !

**Comment by fedebotu** [comment]
Hi! Thanks for your feedback. I updated the extension with the [v1.0.1 release](https://github.com/fedebotu/youchat-google-extension/releases/tag/v1.0.1) - now it should be working fine 😄

**Comment by yarub123** [comment]
@fedebotu Just curious, do I have to go through the cloudflare check each time? 

Because so far I have to keep going to cloudflare and then verify that I am a human 😞

My friends told me I am a human, my browser thinks I am not 😢

**Comment by fedebotu** [comment]
@yarub123 How do I know you are indeed a human? 😆 

Jokes aside, I know it is annoying, but I cannot find a way around it for now. As for that `streamingSearch` file, it is not downloaded using Chrome-based browsers (it is just the query which is parsed)

**Comment by yarub123** [comment]
LOL I can be a human if you want, my program is the closest to a sentient
and conscious human. Turn left at the stop sign, oops sorry, typo in the
algorithm.

And okay thank you human for your response.
