### ISSUE TITLE
Please login and pass Cloudflare check at you.com , help

### ISSUE THREAD

**Issue by Yiton223** [fedebotu/youchat-google-extension#6]

**Comment by fedebotu** [comment]
Hi! Thanks for your feedback. I updated the extension with the [v1.0.1 release](https://github.com/fedebotu/youchat-google-extension/releases/tag/v1.0.1) - now it should be working fine 😄

**Comment by Yiton223** [comment]
thx, work

**Comment by weiqiyue** [comment]
@Yiton223 can you use it? Although I went to check here, I returned a bunch of data and returned to the page without response

**Comment by fedebotu** [comment]
@weiqiyue are you using the Chrome version? If so, it has not been updated yet in the store (it takes ages there, while for Firefox it is lightning fast). You may try waiting for another day or so or try [installing manually](https://github.com/fedebotu/youchat-google-extension#local-install)

**Comment by weiqiyue** [comment]
> @weiqiyue您使用的是 Chrome 版本吗？如果是这样，它还没有在商店中更新（在那里需要很长时间，而对于 Firefox 来说它快如闪电）。您可以尝试等待另一天左右或尝试[手动安装](https://github.com/fedebotu/youchat-google-extension#local-install)
> 
> 编辑：可能我误会你了，如果这堆数据是我想的（API请求），那么回到上一页刷新一下。现在它应该无需刷新即可用于新搜索

Yes, I use Google browser, and then I manually install Google issued, but it is not responding, so sad.And It is the data returned by the api interface. Refresh is invalid.

**Comment by fedebotu** [comment]
If you open this link: https://you.com/api/streamingSearch?q=hi&domain=youchat
Do you see some response like this?
![image](https://user-images.githubusercontent.com/48984123/220808897-d72764cf-e467-472b-a03a-e88062966845.png)

**Comment by weiqiyue** [comment]
> If you open this link: https://you.com/api/streamingSearch?q=hi&domain=youchat Do you see some response like this? ![image](https://user-images.githubusercontent.com/48984123/220808897-d72764cf-e467-472b-a03a-e88062966845.png)

Yes, it is

**Comment by fedebotu** [comment]
I see; here are some other debug options:
- Try changing the page (open a new tab)
- Change query
- Change the search engine
- Make sure some other extension or older version of this extension is not present

**Comment by weiqiyue** [comment]
> I see; here are some other debug options:
> 
> * Try changing the page (open a new tab)
> * Change query
> * Change the search engine
> * Make sure some other extension is not messing around (such as translate)
> * Double-check if the version is correct (v1.0.1, not from Chrome store since it is being reviewed)

I don't know if this is useful. I reinstall it, click the link, and then request it. 403, God
![image](https://user-images.githubusercontent.com/63939219/220810500-94dba26f-153c-42d7-9e8b-fe2a0f4d3ab8.png)

**Comment by weiqiyue** [comment]
> I see; here are some other debug options:
> 
> * Try changing the page (open a new tab)
> * Change query
> * Change the search engine
> * Make sure some other extension is not messing around (such as translate)
> * Double-check if the version is correct (v1.0.1, not from Chrome store since it is being reviewed)

I know, I modified the use-agent of the browser in order to use the new bing on Google, maybe this caused you.com not to recognize me, thank you very much

**Comment by fedebotu** [comment]
@weiqiyue did it work?
Btw, you can try sending me exactly the website and browser you are using + your query, I will try if the error is reproducible

**Comment by 66curiosity99** [comment]
> If you open this link: https://you.com/api/streamingSearch?q=hi&domain=youchat Do you see some response like this? ![image](https://user-images.githubusercontent.com/48984123/220808897-d72764cf-e467-472b-a03a-e88062966845.png)

I see it every time I make a search query.
